Repository Dae-Hwan/BBI-CHUL, pull requests merged in 2021-09, with the labels that each got.

#10 feat: 네비게이션바, 로그인 및 회원가입
  app.py
  decorator.py
  static/css/style.css
  static/js/modal.js
  static/vendor/boxicons/css/animations 2.css
  static/vendor/boxicons/fonts/boxicons 2.eot
  static/vendor/glightbox/css/glightbox 2.css
  static/vendor/php-email-form/validate.js
  templates/index.html
Labels: Type: Feature/Function, Status: In Progress

#21 fix: 로그인 기능
  app.py
  decorator.py
  static/js/calender.js
  static/js/modal.js
  static/weather.js
  templates/calender.html
  templates/index.html
  templates/main.html
Labels: Status: Reviewing

#22 fix: 메인 페이지 html, css수정, 네비게이션 바 오류 수정
  static/js/main.js
  static/vendor/php-email-form/validate.js
  static/weather.css
  templates/main.html
Labels: Type: Feature/Function, Status: In Progress, Status: Reviewing

#23 Feature/mainpage
  static/css/style.css
  static/weather.css
  templates/calender.html
  templates/index.html
  templates/main.html
Labels: Status: In Progress, Priority: Medium

#20 fix : 캘린더 CSS 수정 진행, DB ID연동
  app.py
  static/css/style.css
  static/js/calender.js
  static/weather.js
  templates/calender.html
Labels: Type: Feature/Function, Status: Reviewing

#24 fix: 캘린더 페이지 네비게이션 바 에러 수정
  static/css/style.css
  static/vendor/bootstrap/css/bootstrap.css
  static/weather.css
  templates/calender.html
Labels: Type: Bugfix/Function, Status: Reviewing
