Repository Dae-Hwan/BBI-CHUL, pull requests merged in 2021-10, with the labels that each got.

#38 fix: DB구조를 플렛하게 변경
  app.py
Labels: Priority: High

#42 Feature/mypage
  app.py
  static/css/my_page.css
  static/js/my_page.js
  templates/my_page.html
Labels: Status: In Progress

#45 Feature/calender2
  app.py
  nohup.out
  static/css/calender.css
  static/css/main_page.css
  static/css/my_page.css
  static/css/style.css
  static/css/team_page.css
  static/img/background.png
  static/img/main_backgroung.jpg
  static/js/calender_page.js
  static/js/main_page.js
  static/js/my_page.js
  static/js/team_page.js
  static/vendor/isotope-layout/isotope.pkgd.js
  templates/calender_page.html
  templates/main_page.html
  templates/my_page.html
  templates/team_page.html
Labels: Status: In Progress

#49 feat: DB에서 request.user 수정
  application.py
  decorator.py
  static/css/my_page.css
  static/js/main_page.js
  static/js/my_page.js
  templates/main_page.html
  templates/my_page.html
Labels: Status: In Progress

#51 feat: 마이페이지 회원정보 보안
  application.py
  static/css/my_page.css
  static/js/main_page.js
  static/js/modal.js
  static/js/my_page.js
  templates/main_page.html
  templates/my_page.html
  templates/start_page.html
Labels: Status: In Progress, Priority: High

#50 Feature/countup (메인페이지)
  application.py
  static/css/calender.css
  static/css/main_page.css
  static/css/my_page.css
  static/js/main_page.js
  static/js/modal.js
  templates/calender_page.html
  templates/main_page.html
Labels: Priority: High

#52 Feature/teampage
  application.py
  static/css/team_page.css
  static/js/modal.js
  static/js/team_page.js
  templates/calender_page.html
  templates/team_page.html
Labels: Type: Feature/Function, Priority: High, Status: Reviewing, Type: Feature/Document

#53 feat: 메인페이지 디자인 수정
  static/css/main_page.css
  static/js/main_page.js
  templates/main_page.html
Labels: Priority: Low

#54 Feature/calender2
  application.py
  static/css/calender.css
  static/js/calender_page.js
  templates/calender_page.html
Labels: Status: In Progress
